pipeline:
    docker:
        image: plugins/docker
        dockerfile: Dockerfile
        repo: sirboops/spamd
        experimental: true
        squash: true
        secrets: [ docker_username, docker_password ]
